// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mopfccyzcqdzwenvweyh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1vcGZjY3l6Y3FkendlbnZ3ZXloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0ODQ0NTIsImV4cCI6MjA2MDA2MDQ1Mn0.xe2_Xepq6VtbUH1dekX1k5u3zzdMoxE_1hO9tvXKAWA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);